"""initial_ev_battery_schema

Revision ID: f80d6ea2d176
Revises: 
Create Date: 2026-10-04 13:05:39.605926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80d6ea2d176'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery_packs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('chemistry', sa.String(length=64), nullable=False),
    sa.Column('series_cells', sa.Integer(), nullable=False),
    sa.Column('parallel_strings', sa.Integer(), nullable=False),
    sa.Column('nominal_cell_voltage_v', sa.Float(), nullable=False),
    sa.Column('nominal_cell_capacity_ah', sa.Float(), nullable=False),
    sa.Column('total_voltage_v', sa.Float(), nullable=False),
    sa.Column('total_capacity_ah', sa.Float(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('data_sha256', sa.String(length=64), nullable=False),
    sa.Column('feature_list', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('library_versions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cells',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pack_id', sa.String(length=64), nullable=True),
    sa.Column('cell_index', sa.Integer(), nullable=False),
    sa.Column('cell_serial', sa.String(length=128), nullable=False),
    sa.Column('initial_capacity_ah', sa.Float(), nullable=False),
    sa.Column('nominal_voltage_v', sa.Float(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['battery_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_id', sa.String(length=64), nullable=True),
    sa.Column('pack_id', sa.String(length=64), nullable=True),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pack_id'], ['battery_packs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_id', sa.String(length=64), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_events_cell_id'), 'anomaly_events', ['cell_id'], unique=False)
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_id', sa.String(length=64), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('capacity_ah', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('avg_temp_c', sa.Float(), nullable=False),
    sa.Column('max_temp_c', sa.Float(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycles_cell_id'), 'cycles', ['cell_id'], unique=False)
    op.create_index(op.f('ix_cycles_cycle_number'), 'cycles', ['cycle_number'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_id', sa.String(length=64), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('confidence_interval', sa.Float(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_cell_id'), 'predictions', ['cell_id'], unique=False)
    op.create_table('state_estimates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('soc_ekf', sa.Float(), nullable=False),
    sa.Column('soc_cc', sa.Float(), nullable=False),
    sa.Column('error_bound', sa.Float(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_estimates_cell_id'), 'state_estimates', ['cell_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cell_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('voltage_v', sa.Float(), nullable=False),
    sa.Column('current_a', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('soc_reported', sa.Float(), nullable=True),
    sa.Column('cycle_count', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_cell_id'), 'telemetry', ['cell_id'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_cell_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_state_estimates_cell_id'), table_name='state_estimates')
    op.drop_table('state_estimates')
    op.drop_index(op.f('ix_predictions_cell_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_cycles_cycle_number'), table_name='cycles')
    op.drop_index(op.f('ix_cycles_cell_id'), table_name='cycles')
    op.drop_table('cycles')
    op.drop_index(op.f('ix_anomaly_events_cell_id'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    op.drop_table('alerts')
    op.drop_table('cells')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('model_registry')
    op.drop_table('battery_packs')
    # ### end Alembic commands ###
